name: Push Gem

on:
  push:
    tags:
      - v*

jobs:
  push:
    if: github.repository == 'bdchauvette/nummy'
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # not using ruby 3.3 because of this issue:
          # https://github.com/rubygems/release-gem/issues/2
          ruby-version: '3.2'
          bundler-cache: true

      # Release
      - uses: rubygems/release-gem@v1
